const companyColumns = [
  'uuid',
  'created_at',
  'updated_at',
  'name',
  'memberSince',
  'email',
  'taxationCountry',
  'germanVatNumber',
  'subscriptionFee',
  'commissionFee',
  'registerNumber',
  'legalForm',
  'personAccountable',
  'marketplaces',
  'addressBillingFullName',
  'addressBillingPhone',
  'addressBillingLine1',
  'addressBillingLine2',
  'addressBillingPhone',
  'addressBillingCity',
  'addressBillingState',
  'addressBillingZip',
  'addressBillingCountry',
]

export default companyColumns
